#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
TCR-GIN/arguments.py

Command-line argument parsing and YAML configuration loading for training and
evaluation scripts.

Function
--------
This module:
1. Defines command-line arguments for experiment control, dataset paths, model
   structure, training settings, PISS-specific options, and output paths
2. Optionally loads a YAML configuration file
3. Flattens nested configuration structures into a single-level dictionary
4. Applies argument priority in the following order:
   command line > config file > parser defaults
5. Ensures a valid `experiment_name` is always available

Usage
-----
Example:
    from arguments import parse_args

    args = parse_args()
"""

import os
import yaml
import argparse
from typing import Any, Dict
from pathlib import Path


# ==============================================================================
# Argument parsing
# ==============================================================================
def parse_args():
    """Parse command-line arguments with optional YAML-based defaults."""
    parser = argparse.ArgumentParser(
        description='PISS framework graph regression model training'
    )

    # --------------------------------------------------------------------------
    # Core paths and experiment control
    # --------------------------------------------------------------------------
    parser.add_argument(
        '--config',
        type=str,
        default=None,
        help='Optional configuration file path. Command-line arguments override config values.'
    )
    parser.add_argument(
        '--experiment_name',
        type=str,
        help='Unique experiment name for the current run (usually generated by the runner).'
    )
    parser.add_argument('--seed', type=int, help='Random seed.')
    parser.add_argument('--device', type=str, help='Device: cuda or cpu.')
    parser.add_argument('--num_runs', type=int, help='Number of repeated runs.')
    parser.add_argument(
        '--use_tqdm',
        type=lambda x: str(x).lower() == 'true',
        help='Whether to use a tqdm progress bar.'
    )

    # --------------------------------------------------------------------------
    # Dataset parameters
    # --------------------------------------------------------------------------
    parser.add_argument('--train_path', type=str, help='Training dataset path.')
    parser.add_argument('--val_path', type=str, help='Validation dataset path.')
    parser.add_argument('--test_path', type=str, help='Test dataset path.')
    parser.add_argument('--cache_path', type=str, help='Dataset cache path.')
    parser.add_argument(
        '--rebuild_cache',
        type=lambda x: str(x).lower() == 'true',
        help='Whether to rebuild cached graph files.'
    )

    # --------------------------------------------------------------------------
    # Model structure parameters
    # --------------------------------------------------------------------------
    parser.add_argument(
        '--input_dim',
        type=int,
        help='Input feature dimension (usually inferred by the data loader, but can be set manually).'
    )
    parser.add_argument(
        '--feature_dim',
        type=int,
        default=None,
        help='[Sensitivity] Use only the first N feature dimensions. If None or -1, use all features.'
    )
    parser.add_argument('--hidden_dim', type=int, help='[Grid search] Hidden dimension size.')
    parser.add_argument('--num_layers', type=int, help='[Grid search] Number of GNN layers.')
    parser.add_argument('--dropout', type=float, help='[Grid search] Dropout ratio.')
    parser.add_argument(
        '--jk_type',
        type=str,
        help='[Ablation] JumpingKnowledge type: last, cat, max, or lstm.'
    )
    parser.add_argument(
        '--use_virtual_node',
        type=lambda x: str(x).lower() == 'true',
        help='[Ablation] Whether to use a virtual node.'
    )
    parser.add_argument(
        '--use_residual',
        type=lambda x: str(x).lower() == 'true',
        help='[Ablation] Whether to use residual connections.'
    )
    parser.add_argument(
        '--activation_fn',
        type=str,
        help='[Ablation] Activation function: relu or gelu.'
    )

    # --------------------------------------------------------------------------
    # Training parameters
    # --------------------------------------------------------------------------
    parser.add_argument('--epochs', type=int, help='Maximum number of training epochs.')
    parser.add_argument('--batch_size', type=int, help='Batch size.')
    parser.add_argument('--num_workers', type=int, help='Number of dataloader worker processes.')
    parser.add_argument('--lr', type=float, help='[Grid search] Learning rate.')
    parser.add_argument('--l2_reg', type=float, help='L2 regularization weight.')
    parser.add_argument(
        '--use_lr_scheduler',
        type=lambda x: str(x).lower() == 'true',
        help='Whether to use a learning-rate scheduler.'
    )
    parser.add_argument('--warmup_epochs', type=int, help='Number of warmup epochs.')
    parser.add_argument('--min_lr', type=float, help='Minimum learning rate.')
    parser.add_argument('--eval_steps', type=int, help='Evaluate every N epochs.')
    parser.add_argument(
        '--monitor_metric',
        type=str,
        help='Metric used for early stopping, such as mae or loss.'
    )
    parser.add_argument('--early_stop_patience', type=int, help='Early-stopping patience.')

    # --------------------------------------------------------------------------
    # PISS framework parameters
    # --------------------------------------------------------------------------
    parser.add_argument(
        '--consistency_lambda',
        type=float,
        help='[Sensitivity / Ablation] Consistency-loss weight.'
    )
    parser.add_argument(
        '--piss_k',
        type=int,
        help='[Sensitivity] Number of node-removal operations used to generate positive samples in PISS.'
    )

    # --------------------------------------------------------------------------
    # Output and inference parameters
    # --------------------------------------------------------------------------
    parser.add_argument('--output_dir', type=str, help='Directory for logs and result outputs.')
    parser.add_argument('--model_dir', type=str, help='Directory for saving model checkpoints.')
    parser.add_argument(
        '--model_path',
        type=str,
        help='Inference / validation only: path to a specific model checkpoint (.pt) to load.'
    )

    # --------------------------------------------------------------------------
    # Parsing logic
    # --------------------------------------------------------------------------
    temp_args, _ = parser.parse_known_args()

    defaults = {}
    if temp_args.config:
        print(f"[*] Loading base configuration from file: {temp_args.config}")
        defaults = load_and_flatten_config(temp_args.config)

    parser.set_defaults(**defaults)
    args = parser.parse_args()

    if args.experiment_name is None:
        if args.config:
            args.experiment_name = Path(args.config).stem + "_run"
        else:
            args.experiment_name = "manual_run"

    return args


# ==============================================================================
# Configuration loading
# ==============================================================================
def load_and_flatten_config(config_path: str) -> Dict[str, Any]:
    """
    Load a YAML configuration file and flatten it into a single-level dictionary.

    Supported formats
    -----------------
    1. Training configuration:
       nested under `base_config`
    2. Validation / inference configuration:
       defined directly at the root level
    """
    if not config_path or not os.path.exists(config_path):
        raise FileNotFoundError(f"Configuration file does not exist: {config_path}")

    with open(config_path, 'r', encoding='utf-8') as f:
        config_data = yaml.safe_load(f)

    flat_config = {}

    if 'base_config' in config_data and isinstance(config_data['base_config'], dict):
        for section, params in config_data['base_config'].items():
            if isinstance(params, dict):
                flat_config.update(params)
            else:
                flat_config[section] = params

    ignore_keys = {'base_config', 'experiments', 'instances', 'templates'}
    for key, value in config_data.items():
        if key not in ignore_keys:
            flat_config[key] = value

    return flat_config
